[package]
name = "actix-route-config"
version = "0.1.0"
edition = "2021"
authors = ["Tobias de Bruijn <t.debruijn@array21.dev>"]

[dependencies]
actix-web = { version = "^4.3", default-features = false }